Bakery/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bakery.Models 
{
    public class Treat
    {
        public int TreatId { get; set; }
        
        [Required(ErrorMessage = "Treat must have a name: please add a name.")]
        public string Name { get; set; }
        public ApplicationUser User { get; set; }
        public List<FlavorTreat> FlavorTreats { get; set; }
    }
}

Bakery/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System;
using Bakery.ViewModels;


namespace Bakery.Controllers
{

  public class TreatsController : Controller
  {
    private readonly BakeryContext _db; 
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, BakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
   public async Task<ActionResult> Index()
{
    if (User.Identity.IsAuthenticated)
    {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

        if (currentUser != null)
        {
            List<Treat> userTreats = _db.Treats
                .Where(entry => entry.User.Id == currentUser.Id)
                .ToList();
            return View(userTreats);
        }
    }
        List<Treat> allTreats = _db.Treats.ToList();
      return View(allTreats);
}

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create (Treat treat)
    {
      if (!ModelState.IsValid)
      {
        ModelState.AddModelError("", "Please correct the errors and try again.");
        return View(treat);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                         .Include(treat => treat.FlavorTreats)
                         .ThenInclude(join => join.Flavor)
                         .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Type");
      return View(thisTreat);
    }
    [Authorize]
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => join.FlavorId == treat.TreatId && join.FlavorId == flavorId );
      #nullable disable
      if (flavorId != 0 && joinEntity == null)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = flavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      if (!User.Identity.IsAuthenticated)
      {
        ErrorViewModel error = new ErrorViewModel();
        error.ErrorMessage = "You must be logged in to do that.";
        FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        int treatId = joinEntry.TreatId;
        Dictionary<string, object> model = new Dictionary<string, object>();
        model.Add("error", error);
        model.Add("treatId", treatId);
        return View("Error", model);
      }
      else
      {
        FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreats.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = joinEntry.TreatId });
      }
    }

    [Authorize]
    public ActionResult Edit (int id)
    {
      Treat model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Bakery/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Add a Flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Bakery/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h4>Add a new treat</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)


  <input type="submit" value="Add new treat" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>

Bakery/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Bakery/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models
@model Bakery.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>  


@if(@Model.FlavorTreats.Count == 0)
{
  <p>This treat does not have any flavors yet!</p>
}
else
{
  <h4>This treat has the following tags:</h4>
  <ul>
    @foreach(FlavorTreat join in Model.FlavorTreats)
    {
      <li>Flavor: @join.Flavor.Name</li>
      @using (Html.BeginForm("DeleteJoin", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}
@if (User.Identity.IsAuthenticated)
{
    <p>@Html.ActionLink("Back to list", "Index")</p>
    <p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
    <p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
    <p>@Html.ActionLink("Add flavor", "AddFlavor", new { id = Model.TreatId })</p>
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Bakery/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Edit</h2>

<h4>Edit this Treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Bakery/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models;

<h1>Treats for @User.Identity.Name</h1>

@if (@Model.Count == 0)
{
  <h3>No Treats have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Name", new { id = treat.TreatId }) </li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new Treat", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>